n=int(input('Digite um número inteiro qualquer para ver sua tabuada : '))
print(f'A tabuada de {n} é:')
print(f'{n}x1={n}')
print(f'{n}x2={n*2}')
print(f'{n}x3={n*3}')
print(f'{n}x4={n*4}')
print(f'{n}x5={n*5}')
print(f'{n}x6={n*6}')
print(f'{n}x7={n*7}')
print(f'{n}x8={n*8}')
print(f'{n}x9={n*9}')
print(f'{n}x10={n*10}')